server:
  port: 8443
  ssl:
    key-store: classpath:demoKeystore.p12
    key-store-password: demopass
    key-alias: springboot

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/migration/changelog-master.yaml
    enabled: true

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${EXPIRATION_KEY}

encryption:
  aes:
    keyBase64: ${AES_SECRET_KEY}