
server:
  port: 8443
  ssl:
    key-store: classpath:demoKeystore.p12
    key-store-password: demopass
    key-alias: springboot

spring:
  datasource:
#    url: ${SPRING_DATASOURCE_URL}
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/migration/changelog-master.yaml
    enabled: true

jwt:
  secret: ${jwt-secret-key}
  expiration: ${expiration-key}

encryption:
  aes:
    keyBase64: ${aes-secret-key}
